name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 워크플로우가 레포지토리에 접근할 수 있도록 체크아웃을 진행
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # 안드로이드 프로젝트를 빌드하기 위한 기본 설정
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 11
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      # gradle 빌드 캐싱
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      # gradlew 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # - name: Run unit tests
        # run: ./gradlew testDebugUnitTest

      # - name: Create android test report
        # uses: asadmansr/android-test-report-action@v1.2.0
        # if: ${{ always() }}

      - name: Build assemble release apk
        run: ./gradlew assembleRelease
